<?php
header("Content-Type: application/javascript");

include 'config.php';
?>
const FOOTER = "<?php echo $FOOTER; ?>";
const PROGRAM_NAME = "<?php echo $PROGRAM_NAME; ?>";
const MAINT_QA = "<?php echo $MAINT_QA; ?>";
const MAINT_QA_MYPAGE = "<?php echo $MAINT_QA_MYPAGE; ?>";
const MAINT_QA_USER_LIST = "<?php echo $MAINT_QA_USER_LIST; ?>";
const MAINT_QA_AUTH_P8 = "<?php echo $MAINT_QA_AUTH_P8; ?>";
const MAINT_QA_AUTH_BU = "<?php echo $MAINT_QA_AUTH_BU; ?>";
const MAINT_QA_AUTH_RU = "<?php echo $MAINT_QA_AUTH_RU; ?>";
const MAINT_QA_AUTH_LVT = "<?php echo $MAINT_QA_AUTH_LVT; ?>";
const MAINT_QA_DEVIATION_JOURNAL = "<?php echo $MAINT_QA_DEVIATION_JOURNAL; ?>";

const MAINT_QA_1 = "<?php echo $MAINT_QA_1; ?>";
const MAINT_QA_2 = "<?php echo $MAINT_QA_2; ?>";
const MAINT_QA_3 = "<?php echo $MAINT_QA_3; ?>";
const MAINT_QA_4 = "<?php echo $MAINT_QA_4; ?>";
const MAINT_QA_5 = "<?php echo $MAINT_QA_5; ?>";
const MAINT_QA_6 = "<?php echo $MAINT_QA_6; ?>";
const MAINT_QA_7 = "<?php echo $MAINT_QA_7; ?>";
const MAINT_QA_8 = "<?php echo $MAINT_QA_8; ?>";
const MAINT_QA_9 = "<?php echo $MAINT_QA_9; ?>";
const MAINT_QA_10 = "<?php echo $MAINT_QA_10; ?>";
const MAINT_QA_11 = "<?php echo $MAINT_QA_11; ?>";
const MAINT_QA_12 = "<?php echo $MAINT_QA_12; ?>";
const MAINT_QA_13 = "<?php echo $MAINT_QA_13; ?>";
const MAINT_QA_14 = "<?php echo $MAINT_QA_14; ?>";
const MAINT_QA_15 = "<?php echo $MAINT_QA_15; ?>";
const MAINT_QA_16 = "<?php echo $MAINT_QA_16; ?>";
const MAINT_QA_17 = "<?php echo $MAINT_QA_17; ?>";
const MAINT_QA_18 = "<?php echo $MAINT_QA_18; ?>";
const MAINT_QA_19 = "<?php echo $MAINT_QA_19; ?>";
const MAINT_QA_20 = "<?php echo $MAINT_QA_20; ?>";
const MAINT_QA_1_LINK = "<?php echo $MAINT_QA_1_LINK; ?>";
const MAINT_QA_2_LINK = "<?php echo $MAINT_QA_2_LINK; ?>";
const MAINT_QA_3_LINK = "<?php echo $MAINT_QA_3_LINK; ?>";
const MAINT_QA_4_LINK = "<?php echo $MAINT_QA_4_LINK; ?>";
const MAINT_QA_5_LINK = "<?php echo $MAINT_QA_5_LINK; ?>";
const MAINT_QA_6_LINK = "<?php echo $MAINT_QA_6_LINK; ?>";
const MAINT_QA_7_LINK = "<?php echo $MAINT_QA_7_LINK; ?>";
const MAINT_QA_8_LINK = "<?php echo $MAINT_QA_8_LINK; ?>";
const MAINT_QA_9_LINK = "<?php echo $MAINT_QA_9_LINK; ?>";
const MAINT_QA_10_LINK = "<?php echo $MAINT_QA_10_LINK; ?>";
const MAINT_QA_11_LINK = "<?php echo $MAINT_QA_11_LINK; ?>";
const MAINT_QA_12_LINK = "<?php echo $MAINT_QA_12_LINK; ?>";
const MAINT_QA_13_LINK = "<?php echo $MAINT_QA_13_LINK; ?>";
const MAINT_QA_14_LINK = "<?php echo $MAINT_QA_14_LINK; ?>";
const MAINT_QA_15_LINK = "<?php echo $MAINT_QA_15_LINK; ?>";
const MAINT_QA_16_LINK = "<?php echo $MAINT_QA_16_LINK; ?>";
const MAINT_QA_17_LINK = "<?php echo $MAINT_QA_17_LINK; ?>";
const MAINT_QA_18_LINK = "<?php echo $MAINT_QA_18_LINK; ?>";
const MAINT_QA_19_LINK = "<?php echo $MAINT_QA_19_LINK; ?>";
const MAINT_QA_20_LINK = "<?php echo $MAINT_QA_20_LINK; ?>";